Use rbvmomi2 gem
chef/kitchen-vcenter pull request #174
Opened 2022-12-19 18:33 UTC by ashiqueps

Signed-off-by: Ashique P S <Ashique.saidalavi@progress.com>

## Description

The API wrapper gem used in kitchen-vcenter is `rbvmomi` and it is currently in the public archive and there isn't any development going on. Luckily someone from the community has forked this gem and fixed some of the known issues and published a new version as `rbvmomi2`. 

In this PR, updated the gem spec to use the new gem as a dependency. 

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-12-19 18:33 UTC, ashiqueps commented
PR to update the knife-vsphere gem - https://github.com/chef/knife-vsphere/pull/532

2022-12-20 05:59 UTC, vkarve-chef approved these changes

2022-12-21 05:26 UTC, sanjain-progress approved these changes

2022-12-21 15:14 UTC, tas50 requested changes

2022-12-21 17:30 UTC, ashiqueps commented on kitchen-vcenter.gemspec
> +  spec.add_dependency "rbvmomi2", ">= 1.11", "< 4.0"
Sorry, I haven't noticed that. Updated the version.

2023-01-09 10:07 UTC, merged